name: Deploy Mastra to Vercel
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm mastra build
      - run: pnpm mastra deploy vercel \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --org-id ${{ secrets.VERCEL_ORG_ID }} \
          --project-id ${{ secrets.VERCEL_PROJECT_ID }}
